---
# -- SET DEFAULT SHELL -- #
- name: "set default shell to zsh"
  become: true
  ansible.builtin.user:
    name: "{{ H_USER }}" 
    shell: "/opt/homebrew/bin/zsh"

# -- ENSURE DIRECTORIES -- #
# config directory
- name: "ensure zsh_config_dir exists"
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_env.ZDOTDIR | default(ansible_env.HOME + '/.config/zsh') }}"
    owner: "{{ ansible_env.USER }}"
    mode: "0755"
    force: true
# plugins directory
- name: "ensure $ZDOTDIR/plugins exists"
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_env.ZDOTDIR | default(ansible_env.HOME + '/.config/zsh') }}/plugins"
    owner: "{{ ansible_env.USER }}"
    mode: "0755"
    force: true

# -- SYMLINK ZSH CONFIG FILES -- #
# symlink custom zsh config files
- name: "symlik .zsh files into zsh_config_dir"
  ansible.builtin.file:
    src: "{{ role_path }}/files/zsh/{{ item | basename }}"
    dest: "{{ H_HOME }}/.config/zsh/{{ item | basename }}"
    state: link
    follow: false # apply file operations on the symlink instead of the origin
    force: true
    owner: "{{ H_USER }}"
    mode: "0644"
  with_fileglob:
    - "{{ role_path }}/files/zsh/*.zsh"
# .zshrc
- name: "symlink .zshrc"
  ansible.builtin.file:
    src: "{{ role_path }}/files/zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc" # ansible_env gathers facts about env_vars on the host machine
    state: link # symlink
    follow: false # apply file operations on the symlink instead of the origin
    force: true
    # permissions and ownership
    group: staff
    owner: "{{ ansible_env.USER }}"
    mode: "0644"
# .zshenv
- name: "symlink .zshenv"
  ansible.builtin.file:
    src: "{{ role_path }}/files/zshenv"
    dest: "{{ ansible_env.HOME }}/.zshenv" # ansible_env gathers facts about env_vars on the host machine
    state: link # symlink
    follow: false # apply file operations on the symlink instead of the origin
    force: true
    # permissions and ownership
    group: staff
    owner: "{{ ansible_env.USER }}"
    mode: "0644"
# .zprofile
- name: "symlink .zprofile"
  ansible.builtin.file:
    src: "{{ role_path }}/files/zprofile"
    dest: "{{ ansible_env.HOME }}/.zprofile" # ansible_env gathers facts about env_vars on the host machine
    state: link # symlink
    follow: false # apply file operations on the symlink instead of the origin
    force: true
    # permissions and ownership
    group: staff
    owner: "{{ ansible_env.USER }}"
    mode: "0644"

# -- PLUGINS -- #
- name: "install | fast-syntax-highlighting"
  community.general.homebrew:
    name: "zsh-syntax-highlighting"
    state: latest

# -- THEMES -- #
# fast-syntax-highlighting
- name: "fast-syntax-highlighting"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/catppuccin/zsh-fsh/main/themes/catppuccin-mocha.ini"
    dest: "{{ ansible_env.XDG_CONFIG_HOME | default(ansible_env.HOME + '/.config') }}/themes/catppuccin/zsh-fast-syntax-highlighting.ini"
    owner: "{{ ansible_env.USER }}"
    mode: "0777"
    force: true

# fast-syntax-highlighting
- name: "fast-syntax-highlighting: catppuccin mocha theme"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/catppuccin/zsh-fsh/main/themes/catppuccin-mocha.ini"
    dest: "{{ ansible_env.ZDOTDIR | default(ansible_env.HOME + '/.config/zsh') }}/plugins/fsh/catppuccin-mocha.ini"
    owner: "{{ ansible_env.USER }}"
    mode: "0644"
    force: true
