---
# -- -- -- -- -- -- -- -- #
# --   MAIN PLAYBOOK   -- #
- name: "onesetup"
  # connection
  hosts: localhost
  connection: local
  # variables
  vars_files:
    - group_vars/all/all.yml
    - group_vars/all/env.yml
    - group_vars/all/ssh.yml
  # privilege escalation
  become: true
  become_method: sudo
  become_user: "{{ H_USER }}"
  # pre tasks (running before the roles)
  pre_tasks:
    # -- INCLUDE GROUP_VARS -- #
    # osx / macos
    - name: "group_vars | osx"
      include_vars:
        dir: group_vars/osx
        extensions:
          - yml
          - yaml
      when: ansible_os_family == "Darwin"
    # linux / fedora
    - name: "group_vars | fedora"
      include_vars:
        dir: group_vars/fedora
        extensions:
          - yml
          - yaml
      when: ansible_os_family == "RedHat"
    # -- INCLUDE PRE_TASKS -- #
    # common
    - name: "pre_tasks | common main"
      include_tasks: pre_tasks/common/main.yml
    # osx
    - name: "osx pre_tasks main"
      include_tasks: pre_tasks/osx/main.yml
      when: ansible_os_family == "Darwin"
    - name: "osx pre_tasks tbd"
      include_tasks: pre_tasks/osx/tbd.yml
      when: ansible_os_family == "Darwin"
    # fedora
    - name: "pre_tasks | fedora tbd1"
      include_tasks: pre_tasks/fedora/tbd1.yml
      when: ansible_os_family == "RedHat"
    - name: "pre_tasks | fedora tbd2"
      include_tasks: pre_tasks/fedora/tbd2.yml
      when: ansible_os_family == "RedHat"
  # -- INCLUDE ROLES -- #
  # order of the roles is important (e.g: environment variables need to be set by zsh role before other roles use them)
  roles:
    - { role: zsh, tags: ["zsh"] }
    - { role: apps, tags: ["apps"] }
    - { role: git, tags: ["git"] }
    - { role: ssh, tags: ["ssh"] }
    - { role: alacritty, tags: ["alacritty"] }
    - { role: nvim, tags: ["nvim"] }
    - { role: starship, tags: ["starship"] }
    - { role: fonts, tags: ["fonts"] }
    - { role: browser, tags: ["browser"] }
    - { role: twm, tags: ["twm"] }
    - { role: keymaps, tags: ["keymaps"] }
    - { role: settings, tags: ["settings"] }
