---
# -- dynamically get role directory names -- #
# find role dirs
- name: "find role dirs"
  ansible.builtin.find:
    paths: "{{ ansible_env.ONESETUP }}/roles"
    file_type: directory
    recurse: no
  register: role_dirs
# set role dir names
- name: "set_facts | role names"
  ansible.builtin.set_fact:
    roles_list: "{{ role_dirs.files | map(attribute='path') | map ('basename') | list }}"

# -- debugging --#
- name: "debug"
  ansible.builtin.debug:
    var: roles_list
