---
# -- CLEANUP -- #
# lazygit config dir
- name: "cleanup lazygit config"
  ansible.builtin.file:
    path: "{{ H_XDG_CONFIG_HOME }}/lazygit"
    state: absent
    force: true
  become: true
# gitconfig
- name: "cleanup gitconfig"
  ansible.builtin.file:
    path: "{{ H_HOME }}/.gitconfig"
    state: absent
    force:true
  become: true

# -- SYMLINK -- #
# gitconfig
- name: "symlink gitconfig"
  file:
    src: "{{ role_path }}/files/gitconfig"
    dest: "{{ H_HOME }}/.gitconfig"
    state: link
    force: true
    mode: "0644"
    owner: "{{ H_USER }}"
# lazygit config dir
- name: "symlink lazygit config"
  file:
    src: "{{ role_path }}/files/lazygit/config.yml"
    dest: "{{ H_XDG_CONFIG_HOME }}/lazygit/config.yml"
    state: link
    force: true
    mode: "0600"
    owner: "{{ H_USER }}"
